version: '2'
volumes:
    config:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - "/dev:/dev"
  hass-configurator:
    image: causticlab/hass-configurator-docker:arm
    restart: always
    ports:
      - "8080:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  esphome:
    image: esphome/esphome
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host