name: BalenaCloud Push

on:
  push:
    branches:
      - master

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jbithell/balena-push
        with:
          api-token: ${{secrets.BALENA_API_TOKEN}}
          application-name: ${{secrets.BALENA_APPLICATION_NAME}}